EmineGodek_BrightProje1/EducationApp.MVC/Areas/Admin/Models/ProductListViewModel.cs
namespace EducationApp.MVC.Areas.Admin.Models
{
    public class ProductListViewModel
    {
        public List<ProductViewModel> ProductViewModelList { get; set; }
        public string SourceAction { get; set; }
    }
}

EmineGodek_BrightProje1/EducationApp.MVC/Models/ProductDetailsViewModel.cs
using System;
namespace EducationApp.MVC.Models
{
    public class ProductDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }
        public string InstructorName { get; set; }
        public string InstructorAbout { get; set; }
        public string InstructorUrl { get; set; }
        public List<CategoryViewModel> Categories { get; set; }

        public string Description { get; set; }
    }
}

EmineGodek_BrightProje1/EducationApp.MVC/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EducationApp.Business.Abstract;
using EducationApp.Entity.Concrete;
using EducationApp.Entity.Concrete.ComplexTypes;
using EducationApp.MVC.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EducationApp.MVC.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class CartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartManager;
        private readonly ICartItemService _cartItemManager;
        private readonly IOrderService _orderManager;
        private readonly INotyfService _notyf;

        public CartController(UserManager<User> userManager, ICartService cartManager, INotyfService notyf, ICartItemService cartItemManager, IOrderService orderManager)
        {
            _userManager = userManager;
            _cartManager = cartManager;
            _notyf = notyf;
            _cartItemManager = cartItemManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartManager.GetCartByUserId(userId);
            CartViewModel model = new CartViewModel
            {
                CartId = cart.Id,
                CartItems = cart.CartItems
                    .Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        ProductId = ci.Product.Id,
                        ProductName = ci.Product.Name,
                        ProductUrl = ci.Product.Url,
                        ProductImageUrl = ci.Product.ImageUrl,
                        Price = ci.Product.Price,
                        Quantity = ci.Quantity
                    }).ToList()
            };
            return View(model);
        }
        public async Task<IActionResult> AddToCart(int id, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            await _cartManager.AddToCart(userId, id, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(int cartItemId, int quantity)
        {
            if (ModelState.IsValid)
            {
                await _cartItemManager.ChangeQuantityAsync(cartItemId, quantity);
            }
            else
            {
                _notyf.Warning("Lütfen adedi boş bırakmayınız");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteItemFromCart(int id)
        {
            var cartItem = await _cartItemManager.GetByIdAsync(id);
            _cartItemManager.Delete(cartItem);
            _notyf.Success("Kitap sepetinizden silindi");
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart(int id)
        {
            _cartItemManager.ClearCart(id);
            _notyf.Success("Sepetiniz boşaltılmıştır.");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            string userId = _userManager.GetUserId(User);
            User user = await _userManager.FindByIdAsync(userId);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            OrderViewModel model = new OrderViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                City = user.City,
                PhoneNumber = user.PhoneNumber,
                Email = user.Email,
                Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        ProductId = ci.ProductId,
                        ProductName = ci.Product.Name,
                        Price = ci.Product.Price,
                        Quantity = ci.Quantity,
                        ProductImageUrl = ci.Product.ImageUrl
                    }).ToList()
                },
                CardName = "Emine GÖDEK",
                CardNumber = "5890040000000016",
                ExpirationYear = "2028",
                ExpirationMonth = "10",
                Cvc = "123"
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel model)
        {
            string userId = _userManager.GetUserId(User);
            Cart cart = await _cartManager.GetCartByUserId(userId);
            if (ModelState.IsValid)
            {
                model.Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        ProductId = ci.ProductId,
                        ProductName = ci.Product.Name,
                        Price = ci.Product.Price,
                        ProductImageUrl = ci.Product.ImageUrl,
                        Quantity = ci.Quantity
                    }).ToList()
                };
                Payment payment = PaymentProcess(model);
                if (payment.Status == "success")
                {
                    await SaveOrder(model, userId);
                    _cartItemManager.ClearCart(model.Cart.CartId);
                    _notyf.Success("Ödeme işlemi başarıyla tamamlanmıştır");
                    return RedirectToAction("Index", "Home");
                }
                _notyf.Error("Bir hata oluştu");
            }

            return View();
        }
        [NonAction]
        private Payment PaymentProcess(OrderViewModel model)
        {
            #region Options
            Options options = new Options();
            options.ApiKey = "sandbox-udwhPj75aQQkpFbhnrq8pvtr8JgnTKBr";
            options.SecretKey = "sandbox-bQeFr5qfdnQSbWTPN6MsMPLg70dJd8fa";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            #endregion
            #region Request
            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = "123456789";
            request.Price = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.PaidPrice = Convert.ToInt32(model.Cart.TotalPrice()).ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.Cart.CartId.ToString();
            request.PaymentChannel = PaymentChannel.MOBILE_WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();
            #region PaymentCard
            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;
            #endregion
            #region Buyer
            Buyer buyer = new Buyer();
            buyer.Id = "12345";
            buyer.Name = model.FirstName;
            buyer.Surname = model.LastName;
            buyer.GsmNumber = model.PhoneNumber;
            buyer.Email = model.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = model.Address;
            buyer.Ip = "85.34.78.112";
            buyer.City = model.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;
            #endregion
            #region Addresses
            Address shippingAddress = new Address();
            shippingAddress.ContactName = model.FirstName + " " + model.LastName;
            shippingAddress.City = model.City;
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = model.Address;
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = model.FirstName + " " + model.LastName;
            billingAddress.City = model.City;
            billingAddress.Country = "Turkey";
            billingAddress.Description = model.Address;
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;
            #endregion
            #region Basket Items
            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;
            foreach (var item in model.Cart.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.CartItemId.ToString();
                basketItem.Name = item.ProductName;
                basketItem.Category1 = "Eğitim";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = Convert.ToInt32(item.Price * item.Quantity).ToString();
                basketItems.Add(basketItem);
            }
            request.BasketItems = basketItems;
            #endregion
            #endregion
            Payment payment = Payment.Create(request, options);
            return payment;
        }
        [NonAction]
        private async Task SaveOrder(OrderViewModel model, string userId)
        {

EmineGodek_BrightProje1/EducationApp.MVC/Controllers/EducationAppController.cs
using EducationApp.Business.Abstract;
using EducationApp.Business.Concrete;
using EducationApp.Entity.Concrete;
using EducationApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EducationApp.MVC.Controllers
{
    public class EducationAppController : Controller
    {
        private readonly IProductService _productManager;

        public EducationAppController(IProductService productManager )
        {
            _productManager = productManager;
        }

        public async Task<IActionResult> ProductList(string categoryurl = null, string instructorurl = null)
        {
            List<Product> productList = await _productManager.GetAllActiveProductsAsync(categoryurl, instructorurl);
            List<ProductViewModel> productViewModelList = productList.Select(p => new ProductViewModel
            {
                Id = p.Id,
                Name = p.Name,
                Price = p.Price,
                Url = p.Url,
                ImageUrl = p.ImageUrl,
                InstructorName = p.Instructor.FirstName + " " + p.Instructor.LastName,
                InstructorUrl = p.Instructor.Url,
            }).ToList();
            return View(productViewModelList);
        }
        public async Task<IActionResult> ProductDetails(string url)
        {
            Product product = await _productManager.GetProductByUrlAsync(url);
            ProductDetailsViewModel productDetailsViewModel = new ProductDetailsViewModel
            {
                Id = product.Id,
                Name = product.Name,
                InstructorName = product.Instructor.FirstName + " " + product.Instructor.LastName,
                InstructorAbout = product.Instructor.About,
                InstructorUrl = product.Instructor.Url,
                Url = product.Url,
                ImageUrl = product.ImageUrl,
                Description = product.Description,
                Price = product.Price,
                Categories = product.ProductCategories.Select(bc => new CategoryViewModel
                {
                    Name = bc.Category.Name,
                    Url = bc.Category.Url
                }).ToList()
            };
            return View(productDetailsViewModel);
        }

    }
}

EmineGodek_BrightProje1/EducationApp.MVC/ViewComponents/CategoriesViewComponent.cs
using EducationApp.Business.Abstract;
using EducationApp.Entity.Concrete;
using EducationApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EducationApp.MVC.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryManager;

        public CategoriesViewComponent(ICategoryService categoryManager)
        {
            _categoryManager = categoryManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            CategoryListViewModel categoryListViewModel = new CategoryListViewModel();
            if (RouteData.Values["categoryurl"] != null)
            {
                categoryListViewModel.SelectedCategoryUrl = RouteData.Values["categoryurl"].ToString();
            }
            else
            {
                categoryListViewModel.SelectedCategoryUrl = "";
            }

            List<Category> categories = await _categoryManager.GetAllAsync();
            List<CategoryViewModel> categoryViewModelList = categories
                .Select(c => new CategoryViewModel
                {
                    Name = c.Name,
                    Url = c.Url
                }).ToList();

            categoryListViewModel.CategoryViewModelList = categoryViewModelList;
            return View(categoryListViewModel);
        }
    }
}

EmineGodek_BrightProje1/EducationApp.MVC/Views/EducationApp/ProductDetails.cshtml
@model ProductDetailsViewModel
<!-- Start Contentbar -->
<div class="contentbar">
	<!-- Start row -->
	<div class="row">
		<!-- Start col -->
		<div class="col-md-12 col-lg-12 col-xl-12">
			<div class="card m-b-30">
				<div class="card-body">
					<div class="row">
						<div class="col-lg-5 col-xl-4">
							<div class="product-slider-box product-box-for">
								<img style="width:348px" "height:250px" src="/images/products/@Model.ImageUrl" />
							</div>
						</div>
						<div class="col-lg-4 col-xl-6">
							<p><span class="badge badge-light font-16">Pupular</span></p>
							<h3 class="display-6 fs-4 fw-normal text-danger">@Model.Name</h3>
							<a asp-area=""
							   asp-controller="Home"
							   asp-action="IntructorDetails"
							   asp-route-url="@Model.InstructorUrl">
							</a>
							<p>
								<i class="feather icon-star text-warning"></i>
								<i class="feather icon-star text-warning"></i>
								<i class="feather icon-star text-warning"></i>
								<i class="feather icon-star"></i>
								<i class="feather icon-star"></i>
							</p>
							<div>
								<h4>
									<span class="text-muted text-decoration-line-through">@($"{1000:C0}")</span>
									@($"{Model.Price:C0}")
								</h4>
							</div>
							<div>
								<h3 class="bg-warning p-2 fs-6 text-white fw-bold display-6 mt-3">Eğitim Süresi: 200 Saat</h3>
								
								<p class="fs-6">@Html.Raw(Model.Description)</p>
							</div>
							<div class="button-list mt-5 mb-3 d-flex justify-content-center">

								<form asp-area=""
									  asp-controller="Cart"
									  asp-action="AddToCart"
									  method="post">
									<input type="hidden" asp-for="Id" />
									<button type="submit" class="btn btn-outline-dark ">Sepete Ekle</button>
									<input class="form-control d-inline p-1" style="width:60px;" type="number" name="quantity" min="1" max="9" value="1" />
								</form>

							</div>
						</div>
						<div class="col-lg-3 col-xl-2">
							<img class="img-thumbnail mt-5" src="/images/instructors/1.png" />
							<h3 class="bg-warning p-2 fs-6 text-white fw-bold display-6 mt-3">@Model.InstructorName</h3>
							<p class="fs-6"> <b>Eğitmen Hakkında: </b>@Html.Raw(Model.InstructorAbout)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End col -->
	</div>
	<!-- End row -->
</div>
<!-- End Containerbar -->
<!-- Start js -->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/popper.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/modernizr.min.js"></script>
<script src="assets/js/detect.js"></script>
<script src="assets/js/jquery.slimscroll.js"></script>
<script src="assets/js/vertical-menu.js"></script>
<!-- Switchery js -->
<script src="assets/plugins/switchery/switchery.min.js"></script>
<!-- Slick js -->
<script src="assets/plugins/slick/slick.min.js"></script>
<script src="assets/js/custom/custom-ecommerce-single-product.js"></script>
<!-- Core js -->
<script src="assets/js/core.js"></script>
<!-- End js -->

EmineGodek_BrightProje1/EducationApp.MVC/Views/EducationApp/ProductList.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Education Ana Sayfa";
}
<div class="row">
    <div class="col-2 mt-4">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-10">
        <div class="row g-3">
            @foreach (var productViewModel in Model)
            {
                <div class="col-4 mt-5">
                    @await Html.PartialAsync("_ProductPartial",productViewModel)
                </div>
            }
        </div>
    </div>

</div>